name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install torch numpy tqdm

    - name: Test CNN model
      run: |
        cd cnn
        python -c "from model import CNN; print('CNN import OK')"

    - name: Test RNN model
      run: |
        cd rnn
        python -c "from model import LSTM; print('LSTM import OK')"

    - name: Test Transformer model
      run: |
        cd transformer
        python -c "from model import GPTModel; print('Transformer import OK')"
